#!/bin/zsh
# aws get secrets sm
echo -n "Enter search: "; read search
export AWS_PROFILE=`cat ~/.aws/credentials | grep '\[' | grep -v '#' | tr -d '[' | tr -d ']' | fzf --query "$AWS_PROFILE"`
read -r -d '' CMD1 << EOM
aws secretsmanager get-secret-value --secret-id $(aws secretsmanager list-secrets --filters '[{"Key": "all", "Values": ["'${search}'"]}]' | jq -r ".SecretList | .[].Name" | fzf) | jq -r ".SecretString"
EOM
echo $CMD1 | tee /dev/tty | zsh
