#!/bin/zsh
# aws billing cost
aws ce get-cost-and-usage --time-period Start=${start},End=${end} --granularity MONTHLY --metrics "UnblendedCost" --query 'ResultsByTime[*].Total.UnblendedCost.Amount' --output table
