#!/bin/zsh
# aws get credentials
profile=`cat ~/.aws/credentials | grep '\[' | grep -v '#' | tr -d '[' | tr -d ']' | fzf --query "$AWS_PROFILE"`     
read -r -d '' aws_env  << EOM
export AWS_PROFILE="$profile"
export AWS_REGION="$(aws configure get region --profile $profile)"
export AWS_DEFAULT_REGION="$(aws configure get region --profile $profile)"
export AWS_ACCESS_KEY_ID="$(aws configure get aws_access_key_id --profile $profile)"
export AWS_SECRET_ACCESS_KEY="$(aws configure get aws_secret_access_key --profile $profile)"
export AWS_SESSION_TOKEN="$(aws configure get aws_session_token --profile $profile)"
EOM
echo $aws_env | pbcopy
