#!/bin/zsh
# tgplan terraform terragrunt plan
export UID_TF_MODULES_BASE_PATH="${UID_CN_TF_MODULES_BASE_PATH:-$HOME/Dropbox/git/src/github.com/Ubiquiti-CN}"

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -t|--worktree) ARG_WORKTREE="$2"; shift ;;
    esac
    shift
done

if [ -z "$ARG_WORKTREE" ]; then
    WORKTREE=`ls $UID_TF_MODULES_BASE_PATH | fzf --query "$WORKTREE"`
    if [ -z "$WORKTREE" ]; then
        return false
    fi
else
    WORKTREE=$ARG_WORKTREE
fi

export TG_SRC=$UID_TF_MODULES_BASE_PATH/$WORKTREE/terraform-modules//$(basename $(dirname $PWD))/$(basename $PWD)
echo $TG_SRC
# replace remote git to local git
export remote_git='ssh://git@github.com/Ubiquiti-UID/uid.devops.terraform.git'
export local_git=$devops_terraform_local_git
echo $local_git

# cd ../../../../../../product-uid.terraform-modules//$(basename $(dirname $PWD))/$(basename $PWD)
cd $TG_SRC
# git grep -rli 'git@git.uidev.tools/devops/devops.terraform.git' * | xargs sed -i '' 's|ssh://git@git.uidev.tools/devops/devops.terraform.git|$GIT_MIRROR_PATH/devops.terraform.git|g'
git grep -rli $remote_git * | xargs sed -i '' "s|$remote_git|$local_git|g"
cd -
# end replace
# git -C '$DEV_CONFIG_PATH/ssh' apply uidev.local.patch
[ ! -f .terraform-version ] && echo "0.13.2.1" > .terraform-version

rm -rf .terragrunt-cache
echo "TG_SRC: $TG_SRC"
terragrunt plan --terragrunt-source $TG_SRC -out `pwd`/plan.out 2>&1 && terragrunt show --terragrunt-source $TG_SRC `pwd`/plan.out | tee -a `pwd`/plan-`date +"%Y-%m-%d-%H-%M-%S"`.txt &&  terragrunt show --json --terragrunt-source $TG_SRC `pwd`/plan.out 2>/dev/null | jq -r '([.resource_changes[].change.actions?]|flatten)|{"create":(map(select(.=="create"))|length),"update":(map(select(.=="update"))|length),"delete":(map(select(.=="delete"))|length)}' | tee CHANGES.JSON.txt
# rm -f .terraform-version
# replace back
# cd ../../../../../../product-uid.terraform-modules//$(basename $(dirname $PWD))/$(basename $PWD)
cd $TG_SRC
git grep -rli $local_git * | xargs sed -i '' "s|$local_git|$remote_git|g"
cd -
# end replace
